# Generated by Django 3.2.7 on 2021-10-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog2',
            name='tag',
            field=models.CharField(default='NAN', max_length=50),
        ),
        migrations.AddField(
            model_name='blog2',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
