# Generated by Django 3.2.7 on 2021-10-28 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211027_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='test',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
